version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASS: bazadanni string
      DB_NAME: fintrackdb
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret
      API_KEY: GhcWkPGbSQ53Lt3IViMl8vQZ3t34Hbog
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules 

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazadanni string
      POSTGRES_DB: fintrackdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 