apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-backend
  labels:
    app: fintrack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack-backend
  template:
    metadata:
      labels:
        app: fintrack-backend
    spec:
      containers:
      - name: fintrack-backend
        image: fintrack-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 