apiVersion: v1
kind: Service
metadata:
  name: fintrack-backend
  labels:
    app: fintrack-backend
spec:
  selector:
    app: fintrack-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP 