apiVersion: v1
kind: Service
metadata:
  name: fintrack-frontend
  labels:
    app: fintrack-frontend
spec:
  selector:
    app: fintrack-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer 